CREATE TABLE IF NOT EXISTS "anchor_nps_responses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anchor_nps_responses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"poll_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"score" integer,
	"comment" text,
	"created_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL,
	"updated_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "anchor_poll_choices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anchor_poll_choices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"poll_id" integer NOT NULL,
	"creator_user_id" text NOT NULL,
	"text" text NOT NULL,
	"position" integer NOT NULL,
	"created_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "anchor_poll_votes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anchor_poll_votes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"poll_id" integer NOT NULL,
	"choice_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"created_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "anchor_polls" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anchor_polls_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"channel_id" text NOT NULL,
	"creator_user_id" text NOT NULL,
	"type" text DEFAULT 'poll' NOT NULL,
	"question" text NOT NULL,
	"content" text,
	"anonymous" integer DEFAULT 0 NOT NULL,
	"multi_select" integer DEFAULT 0 NOT NULL,
	"add_choice_setting" text DEFAULT 'no_one' NOT NULL,
	"enabled" integer DEFAULT 1 NOT NULL,
	"message_ts" text,
	"closes_at" bigint,
	"is_current" integer DEFAULT 1 NOT NULL,
	"created_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL,
	"updated_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "appointed_managers" (
	"user_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"added_by" text NOT NULL,
	"added_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL,
	"role" text DEFAULT 'moderator' NOT NULL,
	CONSTRAINT "appointed_managers_pkey" PRIMARY KEY("user_id","channel_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "channel_bans" (
	"user_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"banned_by" text NOT NULL,
	"reason" text,
	"expires" bigint,
	CONSTRAINT "channel_bans_pkey" PRIMARY KEY("user_id","channel_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "embed_blocks" (
	"channel_id" text NOT NULL,
	"type" text NOT NULL,
	"target" text NOT NULL,
	"blocked_by" text NOT NULL,
	"blocked_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL,
	CONSTRAINT "embed_blocks_pkey" PRIMARY KEY("channel_id","type","target"),
	CONSTRAINT "embed_blocks_type_check" CHECK ("embed_blocks"."type" IN ('domain', 'host', 'path'))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "global_admins" (
	"user_id" text PRIMARY KEY NOT NULL,
	"added_by" text NOT NULL,
	"added_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "join_messages" (
	"channel_id" text PRIMARY KEY NOT NULL,
	"message" text NOT NULL,
	"mode" text DEFAULT 'ephemeral' NOT NULL,
	"set_by" text NOT NULL,
	"set_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'anchor_nps_responses_poll_id_fkey') THEN
  ALTER TABLE "anchor_nps_responses" ADD CONSTRAINT "anchor_nps_responses_poll_id_fkey" FOREIGN KEY ("poll_id") REFERENCES "public"."anchor_polls"("id") ON DELETE cascade ON UPDATE no action;
 END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'anchor_poll_choices_poll_id_fkey') THEN
  ALTER TABLE "anchor_poll_choices" ADD CONSTRAINT "anchor_poll_choices_poll_id_fkey" FOREIGN KEY ("poll_id") REFERENCES "public"."anchor_polls"("id") ON DELETE cascade ON UPDATE no action;
 END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'anchor_poll_votes_poll_id_fkey') THEN
  ALTER TABLE "anchor_poll_votes" ADD CONSTRAINT "anchor_poll_votes_poll_id_fkey" FOREIGN KEY ("poll_id") REFERENCES "public"."anchor_polls"("id") ON DELETE cascade ON UPDATE no action;
 END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'anchor_poll_votes_choice_id_fkey') THEN
  ALTER TABLE "anchor_poll_votes" ADD CONSTRAINT "anchor_poll_votes_choice_id_fkey" FOREIGN KEY ("choice_id") REFERENCES "public"."anchor_poll_choices"("id") ON DELETE cascade ON UPDATE no action;
 END IF;
END $$;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "anchor_nps_responses_poll_user" ON "anchor_nps_responses" USING btree ("poll_id","user_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "anchor_poll_choices_position" ON "anchor_poll_choices" USING btree ("poll_id","position");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "anchor_poll_votes_poll" ON "anchor_poll_votes" USING btree ("poll_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "anchor_poll_votes_unique" ON "anchor_poll_votes" USING btree ("poll_id","choice_id","user_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "anchor_polls_channel_current" ON "anchor_polls" USING btree ("channel_id") WHERE "anchor_polls"."is_current" = 1;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "anchor_polls_channel_history" ON "anchor_polls" USING btree ("channel_id","created_at");
