CREATE TABLE "channel_api_keys" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "channel_api_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"channel_id" text NOT NULL,
	"user_id" text NOT NULL,
	"name" text NOT NULL,
	"key_prefix" text NOT NULL,
	"key_hash" text NOT NULL,
	"created_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL,
	"last_used_at" bigint,
	"revoked_at" bigint
);
--> statement-breakpoint
CREATE UNIQUE INDEX "channel_api_keys_hash" ON "channel_api_keys" USING btree ("key_hash");--> statement-breakpoint
CREATE INDEX "channel_api_keys_owner" ON "channel_api_keys" USING btree ("channel_id","user_id") WHERE "channel_api_keys"."revoked_at" IS NULL;