CREATE TABLE "trivia_answers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trivia_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"correct" integer NOT NULL,
	"points" integer NOT NULL,
	"difficulty" text NOT NULL,
	"category" text NOT NULL,
	"created_at" bigint DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint NOT NULL
);
--> statement-breakpoint
CREATE INDEX "trivia_answers_created_at" ON "trivia_answers" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "trivia_answers_filters" ON "trivia_answers" USING btree ("difficulty","category");